FROM node:latest

ENV NPM_CONFIG_LOGLEVEL=http

WORKDIR /app

COPY src /app/src/
COPY package.json .

RUN npm install mongodb-memory-server-global --save-dev

RUN npm install && npm build

STOPSIGNAL SIGINT