name: NodeJS

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: node:latest
    services:
      mongo:
        image: mongo:latest
        environment:
          MONGO_INITDB_ROOT_USERNAME: docker
          MONGO_INITDB_ROOT_PASSWORD: docker
          MONGO_INITDB_DATABASE: casame
        ports:
            - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: in-memory-mongodb install
        run: npm install mongodb-memory-server-global --save-dev
      - name: Test node-server
        env:
          SERVICE_NAME: admin_api
          NODE_ENV: development
          PORT: 5000
          BCRYPT_SALT_ROUNDS: 12
          MONGO_DB_URL_DEVELOPMENT: mongodb://docker:docker@mongo:27017/casame?authSource=admin
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test